blacklist: []
build_space: build/rpi3
catkin_make_args: []
cmake_args:
- -DCMAKE_TOOLCHAIN_FILE=
- -DCMAKE_CROSS_COMPILE_PREFIX=
devel_layout: linked
devel_space: devel/rpi3
extend_path: 
install: true
install_space: install/rpi3
isolate_install: false
jobs_args: []
log_space: logs/rpi3
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
